name = "aiken-lang/multi-sig-wallet"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/multi-sig-wallet'"

[repository]
user = "aiken-lang"
project = "multi-sig-wallet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"



[config]
